#!/usr/bin/env bash

# Install additional composer dependencies as you would from the command line.
# echo "
# Installing Composer Dependencies
# "
# composer require tightenco/mailthief tightenco/quicksand

# To copy standard files to new lambo project place them in ~/.lambo/includes directory.
# echo "
# Copying Include Files
# "
# cp -R ~/.lambo/includes/ $PROJECTPATH

# To add a git commit after given modifications
# echo "
# Committing after modifications to Git
# "
# git add .
# git commit -am "Initialize Composer dependencies and additional files."

composer require barryvdh/laravel-debugbar laravel/telescope laravel/breeze --dev
composer require laravel/horizon

php artisan breeze:install
php artisan horizon:install

php artisan telescope:install

php artisan migrate

npm install && npm run dev

