#!/usr/bin/env bash

PROJECTPATH="."
MESSAGE="Initial commit."
QUIET=false
DEVELOP=false
AUTH=false
NODE=false
CODEEDITOR="code"
BROWSER=""
LINK=false
SECURE=false
FRONTEND="vue"
CREATE_DATABASE=true
DB_USERNAME="root"
DB_PASSWORD="password"
