#!/usr/bin/env bash

PROJECTPATH="."
MESSAGE="Initial commit."
QUIET=false
DEVELOP=false
CODEEDITOR="code"
BROWSER=""
LINK=false
SECURE=false
CREATE_DATABASE=true
DB_USERNAME="root"
# DB_PASSWORD="password"

MIGRATE_DATABASE=yes

# The database host. Defaults to 127.0.0.1.
DB_HOST=127.0.0.1

# The database port. Defaults to 3306.
#DB_PORT=

# The database name. Defaults to the project name.
#DB_NAME=

